In [4]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
## Download apple company data from yfinance
Apple = yf.download("AAPL", start = "2010-01-01", end="2021-01-01")

[*********************100%%**********************]  1 of 1 completed

In [7]:
Apple

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-01-04,7.622500,7.660714,7.585000,7.643214,6.478999,493729600
2010-01-05,7.664286,7.699643,7.616071,7.656429,6.490199,601904800
2010-01-06,7.656429,7.686786,7.526786,7.534643,6.386965,552160000
2010-01-07,7.562500,7.571429,7.466071,7.520714,6.375157,477131200
2010-01-08,7.510714,7.571429,7.466429,7.570714,6.417541,447610800
...,...,...,...,...,...,...
2020-12-24,131.320007,133.460007,131.100006,131.970001,129.679733,54930100
2020-12-28,133.990005,137.339996,133.509995,136.690002,134.317810,124486200
2020-12-29,138.050003,138.789993,134.339996,134.869995,132.529373,121047300
2020-12-30,135.580002,135.990005,133.399994,133.720001,131.399384,96452100
2020-12-31,134.080002,134.740005,131.720001,132.690002,130.387207,99116600

In [9]:
# Download SPY, APPLE, KO companies stocks data from ybinance from 2010 to 2021
ticker=["SPY", "AAPL", "KO"]
stocks = yf.download(ticker, start = "2010-01-01", end="2021-01-01")

[*********************100%%**********************]  3 of 3 completed

In [10]:
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.478999  18.498016   87.129929    7.643214  28.520000
2010-01-05    6.490199  18.274256   87.360565    7.656429  28.174999
2010-01-06    6.386965  18.267767   87.422112    7.534643  28.165001
2010-01-07    6.375157  18.222366   87.791115    7.520714  28.094999
2010-01-08    6.417541  17.885092   88.083275    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  129.679733  48.779106  352.968048  131.970001  53.439999
2020-12-28  134.317810  49.436317  356.000305  136.690002  54.160000
2020-12-29  132.529373  49.408924  355.321136  134.869995  54.130001
2020-12-30  131.399384  49.691887  355.828094  133.720001  54.439999
2020-12-31  130.387207  50.057007  357.635925  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [11]:
# show sample data to get an idea about stocks
stocks.head()

           Adj Close                           Close                         \
                AAPL         KO        SPY      AAPL         KO         SPY
Date
2010-01-04  6.478999  18.498016  87.129929  7.643214  28.520000  113.330002
2010-01-05  6.490199  18.274256  87.360565  7.656429  28.174999  113.629997
2010-01-06  6.386965  18.267767  87.422112  7.534643  28.165001  113.709999
2010-01-07  6.375157  18.222366  87.791115  7.520714  28.094999  114.190002
2010-01-08  6.417541  17.885092  88.083275  7.570714  27.575001  114.570000

                High                              Low                         \
                AAPL         KO         SPY      AAPL         KO         SPY
Date
2010-01-04  7.660714  28.610001  113.389999  7.585000  28.450001  111.510002
2010-01-05  7.699643  28.495001  113.680000  7.616071  28.070000  112.849998
2010-01-06  7.686786  28.219999  113.989998  7.526786  27.990000  113.430000
2010-01-07  7.571429  28.184999  114.330002  7.466071  27.875000  113.180000
2010-01-08  7.571429  27.820000  114.620003  7.466429  27.375000  113.660004

                Open                            Volume
                AAPL         KO         SPY       AAPL        KO        SPY
Date
2010-01-04  7.622500  28.580000  112.370003  493729600  13870400  118944600
2010-01-05  7.664286  28.424999  113.260002  601904800  23172400  111579900
2010-01-06  7.656429  28.174999  113.519997  552160000  19264600  116074400
2010-01-07  7.562500  28.165001  113.500000  477131200  13234600  131091100
2010-01-08  7.510714  27.730000  113.889999  447610800  28712400  126402800

In [12]:
# show stock information
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2769 entries, 2010-01-04 to 2020-12-31
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, AAPL)  2769 non-null   float64
 1   (Adj Close, KO)    2769 non-null   float64
 2   (Adj Close, SPY)   2769 non-null   float64
 3   (Close, AAPL)      2769 non-null   float64
 4   (Close, KO)        2769 non-null   float64
 5   (Close, SPY)       2769 non-null   float64
 6   (High, AAPL)       2769 non-null   float64
 7   (High, KO)         2769 non-null   float64
 8   (High, SPY)        2769 non-null   float64
 9   (Low, AAPL)        2769 non-null   float64
 10  (Low, KO)          2769 non-null   float64
 11  (Low, SPY)         2769 non-null   float64
 12  (Open, AAPL)       2769 non-null   float64
 13  (Open, KO)         2769 non-null   float64
 14  (Open, SPY)        2769 non-null   float64
 15  (Volume, AAPL)     2769 non-null   int64
 16  (Volume, KO)       2769 non-null   int64
 17  (Volume, SPY)      2769 non-null   int64
dtypes: float64(15), int64(3)
memory usage: 411.0 KB

In [13]:
# save stocks into csv
stocks.to_csv("stocksYT.csv")

In [15]:
# read data from csv
stocks = pd.read_csv("stocksYT.csv")
stocks

,Unnamed: 0,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,NaN,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-04,6.478999137878418,18.498016357421875,87.12992858886719,7.643214225769043,28.520000457763672,113.33000183105469,7.660714149475098,28.610000610351562,113.38999938964844,7.585000038146973,28.450000762939453,111.51000213623047,7.622499942779541,28.579999923706055,112.37000274658203,493729600,13870400,118944600
3,2010-01-05,6.490198612213135,18.274255752563477,87.36056518554688,7.656428813934326,28.174999237060547,113.62999725341797,7.699643135070801,28.4950008392334,113.68000030517578,7.6160712242126465,28.06999969482422,112.8499984741211,7.664286136627197,28.424999237060547,113.26000213623047,601904800,23172400,111579900
4,2010-01-06,6.386964797973633,18.26776695251465,87.42211151123047,7.534643173217773,28.165000915527344,113.70999908447266,7.68678617477417,28.219999313354492,113.98999786376953,7.526785850524902,27.989999771118164,113.43000030517578,7.656428813934326,28.174999237060547,113.5199966430664,552160000,19264600,116074400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2766,2020-12-24,129.6797332763672,48.77910614013672,352.9680480957031,131.97000122070312,53.439998626708984,369.0,133.4600067138672,53.54999923706055,369.0299987792969,131.10000610351562,53.02000045776367,367.45001220703125,131.32000732421875,53.02000045776367,368.0799865722656,54930100,3265500,26457900
2767,2020-12-28,134.31781005859375,49.436317443847656,356.00030517578125,136.69000244140625,54.15999984741211,372.1700134277344,137.33999633789062,54.439998626708984,372.5899963378906,133.50999450683594,53.72999954223633,371.07000732421875,133.99000549316406,53.849998474121094,371.739990234375,124486200,9020500,39000400
2768,2020-12-29,132.5293731689453,49.4089241027832,355.3211364746094,134.8699951171875,54.130001068115234,371.4599914550781,138.7899932861328,54.4900016784668,374.0,134.33999633789062,54.02000045776367,370.8299865722656,138.0500030517578,54.45000076293945,373.80999755859375,121047300,8320600,53680500
2769,2020-12-30,131.39938354492188,49.69188690185547,355.8280944824219,133.72000122070312,54.439998626708984,371.989990234375,135.99000549316406,54.630001068115234,373.1000061035156,133.39999389648438,54.029998779296875,371.57000732421875,135.5800018310547,54.04999923706055,372.3399963378906,96452100,8142700,49455300
2770,2020-12-31,130.38720703125,50.0570068359375,357.63592529296875,132.69000244140625,54.84000015258789,373.8800048828125,134.74000549316406,54.93000030517578,374.6600036621094,131.72000122070312,54.27000045776367,371.2300109863281,134.0800018310547,54.45000076293945,371.7799987792969,99116600,8495000,78520700

In [16]:
# show header into 2 line - make easier to read
stocks = pd.read_csv("stocksYT.csv", header=[0,1])
stocks

     Unnamed: 0_level_0   Adj Close                              Close  \
     Unnamed: 0_level_1        AAPL         KO         SPY        AAPL
0                  Date         NaN        NaN         NaN         NaN
1            2010-01-04    6.478999  18.498016   87.129929    7.643214
2            2010-01-05    6.490199  18.274256   87.360565    7.656429
3            2010-01-06    6.386965  18.267767   87.422112    7.534643
4            2010-01-07    6.375157  18.222366   87.791115    7.520714
...                 ...         ...        ...         ...         ...
2765         2020-12-24  129.679733  48.779106  352.968048  131.970001
2766         2020-12-28  134.317810  49.436317  356.000305  136.690002
2767         2020-12-29  132.529373  49.408924  355.321136  134.869995
2768         2020-12-30  131.399384  49.691887  355.828094  133.720001
2769         2020-12-31  130.387207  50.057007  357.635925  132.690002

                                   High                                Low  \
             KO         SPY        AAPL         KO         SPY        AAPL
0           NaN         NaN         NaN        NaN         NaN         NaN
1     28.520000  113.330002    7.660714  28.610001  113.389999    7.585000
2     28.174999  113.629997    7.699643  28.495001  113.680000    7.616071
3     28.165001  113.709999    7.686786  28.219999  113.989998    7.526786
4     28.094999  114.190002    7.571429  28.184999  114.330002    7.466071
...         ...         ...         ...        ...         ...         ...
2765  53.439999  369.000000  133.460007  53.549999  369.029999  131.100006
2766  54.160000  372.170013  137.339996  54.439999  372.589996  133.509995
2767  54.130001  371.459991  138.789993  54.490002  374.000000  134.339996
2768  54.439999  371.989990  135.990005  54.630001  373.100006  133.399994
2769  54.840000  373.880005  134.740005  54.930000  374.660004  131.720001

                                   Open                              Volume  \
             KO         SPY        AAPL         KO         SPY         AAPL
0           NaN         NaN         NaN        NaN         NaN          NaN
1     28.450001  111.510002    7.622500  28.580000  112.370003  493729600.0
2     28.070000  112.849998    7.664286  28.424999  113.260002  601904800.0
3     27.990000  113.430000    7.656429  28.174999  113.519997  552160000.0
4     27.875000  113.180000    7.562500  28.165001  113.500000  477131200.0
...         ...         ...         ...        ...         ...          ...
2765  53.020000  367.450012  131.320007  53.020000  368.079987   54930100.0
2766  53.730000  371.070007  133.990005  53.849998  371.739990  124486200.0
2767  54.020000  370.829987  138.050003  54.450001  373.809998  121047300.0
2768  54.029999  371.570007  135.580002  54.049999  372.339996   96452100.0
2769  54.270000  371.230011  134.080002  54.450001  371.779999   99116600.0


              KO          SPY
0            NaN          NaN
1     13870400.0  118944600.0
2     23172400.0  111579900.0
3     19264600.0  116074400.0
4     13234600.0  131091100.0
...          ...          ...
2765   3265500.0   26457900.0
2766   9020500.0   39000400.0
2767   8320600.0   53680500.0
2768   8142700.0   49455300.0
2769   8495000.0   78520700.0

[2770 rows x 19 columns]

In [17]:
# make easier to read 
stocks = pd.read_csv("stocksYT.csv", header=[0,1], index_col=[0])
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.478999  18.498016   87.129929    7.643214  28.520000
2010-01-05    6.490199  18.274256   87.360565    7.656429  28.174999
2010-01-06    6.386965  18.267767   87.422112    7.534643  28.165001
2010-01-07    6.375157  18.222366   87.791115    7.520714  28.094999
2010-01-08    6.417541  17.885092   88.083275    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  129.679733  48.779106  352.968048  131.970001  53.439999
2020-12-28  134.317810  49.436317  356.000305  136.690002  54.160000
2020-12-29  132.529373  49.408924  355.321136  134.869995  54.130001
2020-12-30  131.399384  49.691887  355.828094  133.720001  54.439999
2020-12-31  130.387207  50.057007  357.635925  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [18]:
stocks = pd.read_csv("stocksYT.csv", header=[0,1], index_col=[0], parse_dates=[0])
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.478999  18.498016   87.129929    7.643214  28.520000
2010-01-05    6.490199  18.274256   87.360565    7.656429  28.174999
2010-01-06    6.386965  18.267767   87.422112    7.534643  28.165001
2010-01-07    6.375157  18.222366   87.791115    7.520714  28.094999
2010-01-08    6.417541  17.885092   88.083275    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  129.679733  48.779106  352.968048  131.970001  53.439999
2020-12-28  134.317810  49.436317  356.000305  136.690002  54.160000
2020-12-29  132.529373  49.408924  355.321136  134.869995  54.130001
2020-12-30  131.399384  49.691887  355.828094  133.720001  54.439999
2020-12-31  130.387207  50.057007  357.635925  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [19]:
stocks.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close',   'KO'),
            ('Adj Close',  'SPY'),
            (    'Close', 'AAPL'),
            (    'Close',   'KO'),
            (    'Close',  'SPY'),
            (     'High', 'AAPL'),
            (     'High',   'KO'),
            (     'High',  'SPY'),
            (      'Low', 'AAPL'),
            (      'Low',   'KO'),
            (      'Low',  'SPY'),
            (     'Open', 'AAPL'),
            (     'Open',   'KO'),
            (     'Open',  'SPY'),
            (   'Volume', 'AAPL'),
            (   'Volume',   'KO'),
            (   'Volume',  'SPY')],
           )

In [21]:
# convert multi index to one tuple
stocks.columns = stocks.columns.to_flat_index()
stocks.columns

Index([('Adj Close', 'AAPL'),   ('Adj Close', 'KO'),  ('Adj Close', 'SPY'),
           ('Close', 'AAPL'),       ('Close', 'KO'),      ('Close', 'SPY'),
            ('High', 'AAPL'),        ('High', 'KO'),       ('High', 'SPY'),
             ('Low', 'AAPL'),         ('Low', 'KO'),        ('Low', 'SPY'),
            ('Open', 'AAPL'),        ('Open', 'KO'),       ('Open', 'SPY'),
          ('Volume', 'AAPL'),      ('Volume', 'KO'),     ('Volume', 'SPY')],
      dtype='object')

In [22]:
stocks

,"(Adj Close, AAPL)","(Adj Close, KO)","(Adj Close, SPY)","(Close, AAPL)","(Close, KO)","(Close, SPY)","(High, AAPL)","(High, KO)","(High, SPY)","(Low, AAPL)","(Low, KO)","(Low, SPY)","(Open, AAPL)","(Open, KO)","(Open, SPY)","(Volume, AAPL)","(Volume, KO)","(Volume, SPY)"
Date,,,,,,,,,,,,,,,,,,
2010-01-04,6.478999,18.498016,87.129929,7.643214,28.520000,113.330002,7.660714,28.610001,113.389999,7.585000,28.450001,111.510002,7.622500,28.580000,112.370003,493729600,13870400,118944600
2010-01-05,6.490199,18.274256,87.360565,7.656429,28.174999,113.629997,7.699643,28.495001,113.680000,7.616071,28.070000,112.849998,7.664286,28.424999,113.260002,601904800,23172400,111579900
2010-01-06,6.386965,18.267767,87.422112,7.534643,28.165001,113.709999,7.686786,28.219999,113.989998,7.526786,27.990000,113.430000,7.656429,28.174999,113.519997,552160000,19264600,116074400
2010-01-07,6.375157,18.222366,87.791115,7.520714,28.094999,114.190002,7.571429,28.184999,114.330002,7.466071,27.875000,113.180000,7.562500,28.165001,113.500000,477131200,13234600,131091100
2010-01-08,6.417541,17.885092,88.083275,7.570714,27.575001,114.570000,7.571429,27.820000,114.620003,7.466429,27.375000,113.660004,7.510714,27.730000,113.889999,447610800,28712400,126402800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,129.679733,48.779106,352.968048,131.970001,53.439999,369.000000,133.460007,53.549999,369.029999,131.100006,53.020000,367.450012,131.320007,53.020000,368.079987,54930100,3265500,26457900
2020-12-28,134.317810,49.436317,356.000305,136.690002,54.160000,372.170013,137.339996,54.439999,372.589996,133.509995,53.730000,371.070007,133.990005,53.849998,371.739990,124486200,9020500,39000400
2020-12-29,132.529373,49.408924,355.321136,134.869995,54.130001,371.459991,138.789993,54.490002,374.000000,134.339996,54.020000,370.829987,138.050003,54.450001,373.809998,121047300,8320600,53680500
2020-12-30,131.399384,49.691887,355.828094,133.720001,54.439999,371.989990,135.990005,54.630001,373.100006,133.399994,54.029999,371.570007,135.580002,54.049999,372.339996,96452100,8142700,49455300
2020-12-31,130.387207,50.057007,357.635925,132.690002,54.840000,373.880005,134.740005,54.930000,374.660004,131.720001,54.270000,371.230011,134.080002,54.450001,371.779999,99116600,8495000,78520700

In [24]:
# con
stocks.columns = pd.MultiIndex.from_tuples(stocks.columns)
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2010-01-04    6.478999  18.498016   87.129929    7.643214  28.520000
2010-01-05    6.490199  18.274256   87.360565    7.656429  28.174999
2010-01-06    6.386965  18.267767   87.422112    7.534643  28.165001
2010-01-07    6.375157  18.222366   87.791115    7.520714  28.094999
2010-01-08    6.417541  17.885092   88.083275    7.570714  27.575001
...                ...        ...         ...         ...        ...
2020-12-24  129.679733  48.779106  352.968048  131.970001  53.439999
2020-12-28  134.317810  49.436317  356.000305  136.690002  54.160000
2020-12-29  132.529373  49.408924  355.321136  134.869995  54.130001
2020-12-30  131.399384  49.691887  355.828094  133.720001  54.439999
2020-12-31  130.387207  50.057007  357.635925  132.690002  54.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2010-01-04  113.330002    7.660714  28.610001  113.389999    7.585000
2010-01-05  113.629997    7.699643  28.495001  113.680000    7.616071
2010-01-06  113.709999    7.686786  28.219999  113.989998    7.526786
2010-01-07  114.190002    7.571429  28.184999  114.330002    7.466071
2010-01-08  114.570000    7.571429  27.820000  114.620003    7.466429
...                ...         ...        ...         ...         ...
2020-12-24  369.000000  133.460007  53.549999  369.029999  131.100006
2020-12-28  372.170013  137.339996  54.439999  372.589996  133.509995
2020-12-29  371.459991  138.789993  54.490002  374.000000  134.339996
2020-12-30  371.989990  135.990005  54.630001  373.100006  133.399994
2020-12-31  373.880005  134.740005  54.930000  374.660004  131.720001

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2010-01-04  28.450001  111.510002    7.622500  28.580000  112.370003
2010-01-05  28.070000  112.849998    7.664286  28.424999  113.260002
2010-01-06  27.990000  113.430000    7.656429  28.174999  113.519997
2010-01-07  27.875000  113.180000    7.562500  28.165001  113.500000
2010-01-08  27.375000  113.660004    7.510714  27.730000  113.889999
...               ...         ...         ...        ...         ...
2020-12-24  53.020000  367.450012  131.320007  53.020000  368.079987
2020-12-28  53.730000  371.070007  133.990005  53.849998  371.739990
2020-12-29  54.020000  370.829987  138.050003  54.450001  373.809998
2020-12-30  54.029999  371.570007  135.580002  54.049999  372.339996
2020-12-31  54.270000  371.230011  134.080002  54.450001  371.779999

               Volume
                 AAPL        KO        SPY
Date
2010-01-04  493729600  13870400  118944600
2010-01-05  601904800  23172400  111579900
2010-01-06  552160000  19264600  116074400
2010-01-07  477131200  13234600  131091100
2010-01-08  447610800  28712400  126402800
...               ...       ...        ...
2020-12-24   54930100   3265500   26457900
2020-12-28  124486200   9020500   39000400
2020-12-29  121047300   8320600   53680500
2020-12-30   96452100   8142700   49455300
2020-12-31   99116600   8495000   78520700

[2769 rows x 18 columns]

In [25]:
stocks.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close',   'KO'),
            ('Adj Close',  'SPY'),
            (    'Close', 'AAPL'),
            (    'Close',   'KO'),
            (    'Close',  'SPY'),
            (     'High', 'AAPL'),
            (     'High',   'KO'),
            (     'High',  'SPY'),
            (      'Low', 'AAPL'),
            (      'Low',   'KO'),
            (      'Low',  'SPY'),
            (     'Open', 'AAPL'),
            (     'Open',   'KO'),
            (     'Open',  'SPY'),
            (   'Volume', 'AAPL'),
            (   'Volume',   'KO'),
            (   'Volume',  'SPY')],
           )

In [26]:
stocks.describe()

         Adj Close                                  Close               \
              AAPL           KO          SPY         AAPL           KO
count  2769.000000  2769.000000  2769.000000  2769.000000  2769.000000
mean     31.562566    32.208758   182.052367    33.777537    41.320121
std      24.614793     8.183724    69.703575    24.572747     6.808527
min       5.814175    16.373823    79.271935     6.858929    25.014999
25%      15.201318    26.605543   114.881264    17.484285    37.660000
50%      24.549253    31.768911   175.981049    26.987499    41.759998
75%      40.931637    37.628517   241.932785    43.007500    45.549999
max     134.317810    53.069550   357.635925   136.690002    60.130001

                           High                                    Low  \
               SPY         AAPL           KO          SPY         AAPL
count  2769.000000  2769.000000  2769.000000  2769.000000  2769.000000
mean    207.676797    34.114230    41.583236   208.716963    33.413543
std      67.240791    24.895185     6.864731    67.589965    24.220789
min     102.199997     7.000000    25.150000   103.419998     6.794643
25%     141.559998    17.695356    37.919998   142.100006    17.333929
50%     205.210007    27.225000    41.980000   206.190002    26.705000
75%     265.339996    43.367500    45.799999   267.320007    42.605000
max     373.880005   138.789993    60.130001   378.459991   134.339996

                                        Open                            \
                KO          SPY         AAPL           KO          SPY
count  2769.000000  2769.000000  2769.000000  2769.000000  2769.000000
mean     41.042551   206.475522    33.764375    41.314411   207.648136
std       6.755616    66.883703    24.561595     6.807492    67.258092
min      24.735001   101.129997     6.870357    25.110001   103.110001
25%      37.419998   140.929993    17.518213    37.700001   141.660004
50%      41.529999   204.110001    26.975000    41.750000   204.960007
75%      45.310001   263.390015    43.012501    45.549999   265.779999
max      59.619999   371.570007   138.050003    59.810001   373.809998

             Volume
               AAPL            KO           SPY
count  2.769000e+03  2.769000e+03  2.769000e+03
mean   2.866162e+08  1.502133e+07  1.244573e+08
std    2.289459e+08  6.716946e+06  7.477756e+07
min    4.544800e+07  2.996300e+06  2.027000e+07
25%    1.211120e+08  1.071810e+07  7.292670e+07
50%    2.029972e+08  1.350830e+07  1.045961e+08
75%    3.890376e+08  1.751480e+07  1.539926e+08
max    1.880998e+09  9.896750e+07  7.178287e+08